import 'package:flutter_test/flutter_test.dart';
import 'package:syncfusion_easy_reports/syncfusion_easy_reports.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('Excel Template Generation & Import Tests', () {
    late ExcelTemplateService service;

    setUp(() {
      service = ExcelTemplateService();
    });

    test(
      'Should generate binary XLSX data-entry template with instructions',
      () async {
        final columns = [
          ExcelTemplateColumn(
            name: 'Employee ID',
            sampleValue: 'EMP001',
            isRequired: true,
          ),
          ExcelTemplateColumn(
            name: 'Full Name',
            sampleValue: 'John Doe',
            isRequired: true,
          ),
          ExcelTemplateColumn(
            name: 'Department',
            sampleValue: 'Engineering',
            dropdownList: ['Engineering', 'Marketing', 'Sales'],
          ),
          ExcelTemplateColumn(
            name: 'Salary',
            sampleValue: '75000',
            isRequired: true,
          ),
        ];

        final bytes = await service.generateXlsxTemplate(
          columns: columns,
          instructions:
              'Please fill out all mandatory fields marked with an asterisk (*).',
        );

        expect(bytes, isNotEmpty);
        expect(bytes.length, greaterThan(100));

        // Import the generated bytes back and verify
        final result = service.importExcelBytes(
          bytes,
          expectedColumns: columns,
        );
        expect(result.isValid, isTrue);
        expect(result.records, isNotEmpty);
        expect(result.records.first['Employee ID'], 'EMP001');
        expect(result.records.first['Salary'], 75000);
      },
    );

    test(
      'Should detect missing required columns during template import',
      () async {
        final columns = [
          ExcelTemplateColumn(name: 'ID', sampleValue: '001', isRequired: true),
          ExcelTemplateColumn(
            name: 'Name',
            sampleValue: 'Test',
            isRequired: true,
          ),
        ];

        final incompleteColumns = [
          ExcelTemplateColumn(name: 'ID', sampleValue: '001', isRequired: true),
          // 'Name' is missing
        ];

        final bytes = await service.generateXlsxTemplate(
          columns: incompleteColumns,
        );
        final result = service.importExcelBytes(
          bytes,
          expectedColumns: columns,
        );

        expect(result.isValid, isFalse);
        expect(result.hasErrors, isTrue);
        expect(result.errors.any((e) => e.columnName == 'Name'), isTrue);
      },
    );
  });
}
