import 'dart:convert';
import 'package:logging/logging.dart';

import '../downloader/downloader.dart';

/// Lightweight JSON-backed template generator for tests and example flows.
///
/// NOTE: This intentionally avoids heavy binary Excel generation to keep
/// analysis and CI fast. For production-grade XLSX output, replace with a
/// Syncfusion or excel generator implementation.
class ExcelTemplateColumn {
  final String name;
  final String sampleValue;
  final List<String>? dropdownList;
  final String? dropdownFormula;

  ExcelTemplateColumn({
    required this.name,
    required this.sampleValue,
    this.dropdownList,
    this.dropdownFormula,
  });
}

class ExcelTemplateService {
  static final Logger _log = Logger('ExcelTemplateService');

  /// Generates a small JSON-based "template" payload returned as bytes.
  Future<List<int>> generateTemplate({
    required List<ExcelTemplateColumn> columns,
    Map<String, List<String>>? lookupLists,
  }) async {
    final Map<String, dynamic> doc = {
      'columns': columns
          .map(
            (c) => {
              'name': c.name,
              'sample': c.sampleValue,
              'dropdown': c.dropdownList,
              'formula': c.dropdownFormula,
            },
          )
          .toList(),
      'lookups': lookupLists ?? {},
    };

    final bytes = utf8.encode(jsonEncode(doc));
    return bytes;
  }

  Future<void> generateAndDownloadTemplate({
    required List<ExcelTemplateColumn> columns,
    Map<String, List<String>>? lookupLists,
    required String filename,
  }) async {
    final bytes = await generateTemplate(
      columns: columns,
      lookupLists: lookupLists,
    );
    final fullFilename = filename.endsWith('.xlsx')
        ? filename
        : '$filename.xlsx';
    final downloader = FileDownloader();
    await downloader.downloadFile(
      bytes,
      fullFilename,
      mimeType:
          'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    );
  }

  /// Parses bytes generated by [generateTemplate] back to a list of records
  /// where each record represents the sample row.
  List<Map<String, dynamic>> parseExcelBytes(List<int> bytes) {
    try {
      final decoded = jsonDecode(utf8.decode(bytes)) as Map<String, dynamic>;
      final List cols = decoded['columns'] as List? ?? [];

      if (cols.isEmpty) return [];

      final Map<String, dynamic> record = {};
      for (final c in cols) {
        final name = c['name'] as String? ?? 'col';
        final sample = c['sample']?.toString() ?? '';
        record[name] = _autoType(sample);
      }

      return [record];
    } catch (e) {
      _log.warning('Failed to parse template bytes: $e');
      return [];
    }
  }

  /// Simple picker wrapper used by the example. Returns `null` on unsupported
  /// platforms or when the user cancels — this keeps the example UI functional
  /// without pulling in heavy native picker logic for tests.
  Future<List<Map<String, dynamic>>?> pickAndParseExcel() async {
    _log.info(
      'pickAndParseExcel called - not implemented in lightweight service',
    );
    return null;
  }

  dynamic _autoType(String value) {
    final val = value.trim();
    if (val.isEmpty) return null;
    if (val.toLowerCase() == 'true') return true;
    if (val.toLowerCase() == 'false') return false;
    final num? n = num.tryParse(val);
    if (n != null) return n;
    return val;
  }
}
